# Generated by Django 2.1 on 2018-08-16 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messsage', models.TextField(max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('message_uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_message', to='Login.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_comment', to='Login.Message'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_comment', to='Login.User'),
        ),
    ]
