# Generated by Django 2.1 on 2018-08-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20180816_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messsage',
            new_name='message',
        ),
    ]
