# Generated by Django 2.1 on 2018-08-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20180816_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
    ]
